language: ruby
rvm:
- 1.9.3
script: bundle exec jekyll build
install: bundle install
after_success: bundle exec s3_website push
dd:
  secure: czGcpOUUwx08Fwv7+UDcgaNoIL74IlrNhEqeQlgl9i2+h3xZYmUKKsYNHl3SLGbcIlQtq7mjcvqAYhoj8sEOJFXK/BLR5GN1CWVwVyCg5RDKjXF9jX6o3iZz+uJtN1FfmIpdzbvyl6Rj7soVDcgFURs8/SR0cY7AyogjZU594Pg=
