# Site settings
title: Team Olympus Games Blog
email: email?
description: > # this means to ignore newlines until "baseurl:"
  Blogging about random stuff since last week
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://teamolympusgames.com" # the base hostname & protocol for your site
twitter_username: twitter?
github_username:  github?

# Build settings
markdown: kramdown
